services:
  api:
    platform: linux/amd64
    build: .
    container_name: twitter-api
    ports:
      - 8000:8000
    environment:
      - DISPLAY=:99.0
      - DISPLAY_NUM=99
      - TWITTER_EMAIL=${TWITTER_USER}
      - TWITTER_USER=${TWITTER_USER}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
    volumes:
      - ./src:/code/src
      - ./.session:/code/.session
      - /tmp/.X11-unix:/tmp/.X11-unix
    
    # command: 'xvfb-run --server-args="-screen 0 1900x1200x24" python3 src/api.py'
    # command: ["python3", "src/api.py"]
    # command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    command: ["xvfb-run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    # tty: true