# 
FROM python:3.12

RUN pip install pytest-playwright
RUN playwright install

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./src /code/src

# 
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]