services:
  api:
    build: .
    container_name: twitter-api
    ports:
      - 8000:8000
    environment:
      - DISPLAY=:0
      - TWITTER_EMAIL = ${TWITTER_USER}
      - TWITTER_USER = ${TWITTER_USER}
      - TWITTER_PASSWORD = ${TWITTER_PASSWORD}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix